---
title: "Coverage Gaps in Canada’s PM~2.5~ Monitoring Network and Recommendations for Network Expansion"
subtitle: "How can we improve access to smoke monitoring in Canada?"
author: 
  - name: "Brayden Nilson"
    affiliations: "Applied Air Quality Scientist, ECCC (AQ Science Unit - West)"
date: 2026-06-11
date-format: "MMMM D, YYYY"
---

# Background

## PM~2.5~ monitoring is costly, but access to real-time information is crucial during smoke events

<!-- costs of PM~2.5~ monitoring -->
<!-- justification for real-time monitoring access -->
<!-- image of FEM station -->

## *Low-cost monitors* (PurpleAir, AQegg, etc) are a cost effective means to supplement monitoring

<!-- costs of PurpleAir -->
<!-- existing PA network -->
<!-- AQSU work? -->
<!-- image of PA, or AQmap? -->

## It is difficult to determine individual access to monitoring data, but gaps do exist

- Who needs access?
- What maximum distance to a monitor do we want?
- Is it possible to reasonably cover everyone?

<!-- remove "but gaps do exist" or add image to justify -->

# Input Data

## Identified who needs access using community locations and gridded Census population

<!-- 2016 Census used due to availability of gridded data -->

## Considered existing regulatory (*NAPS FEM*) and PurpleAir monitors with PM~2.5~ data

 <!-- required 1+ observations during month of analysis (May 2026 here) -->

## Assumed possible to install a new monitor at any community (*not always true!*)

# Existing Network Coverage

## Including both population and communities as coverage targets allows for equitable assessments

<!-- maybe cache a copy so stays static? -->

{{< iframe "https://aqmap.ca/aqmap/reports/gap_analysis/input_summary_table/index.html" >}}

## The existing monitoring networks cover ~91% of Canadians, but only ~50-60% of communities

<!-- maybe cache a copy so stays static? or derive numbers from within table html -->

{{< iframe "https://aqmap.ca/aqmap/reports/gap_analysis/current_coverage_table/index.html" >}}

# Suggested Install Locations

## I suggest potential communities where a monitor could be installed to cover gaps

<!-- maybe cache a copy so stays static? -->

{{< iframe "https://aqmap.ca/aqmap/reports/gap_analysis/suggested_install_tables/CAN/index.html" "82%" >}}

##
<!-- maybe cache a copy so stays static? -->

{{< iframe "https://aqmap.ca/aqmap/reports/gap_analysis/coverage_map/index.html" "100%" >}}

## Installations would occur in stages and can be targeted to meet access goals

{{< iframe "https://aqmap.ca/aqmap/reports/gap_analysis/pm25/index.html#sec-expected-coverage-improvements" >}}

# Conclusion

## This analysis provides guidance for network managers to improve access to PM~2.5~ monitoring

<!-- add hey figures from above -->

Questions? Want access to the report?

> {{< fa envelope >}} brayden.nilson@ec.gc.ca